[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "../types/" }
net-message = { git = "https://github.com/MagicPotatoBean/net-msg-rs" }
anyhow = "1.0.95"
crossterm = "0.28.1"
rsa = "0.9.7"
sha256 = "1.5.0"
