cargo-features = ["edition2024"]
[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
rsa = { version = "0.9.7", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"]}
soft-aes = "0.2.2"
type_hash = "0.3.0"
