name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-client-ubuntu:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --bin client --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: irc-ubuntu
        path: target/release/client

  build-client-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --bin client --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: irc-windows
        path: target/release/client.exe
